## MQ
1. 死信队列
	1. 存储由于某些异常（消息被拒绝、消息过期、队列达到最大长度、重试次数达到上限）而无法被正常消费的信息
2. 一条消息一直消费失败如何处理？
	1. 看log分析，是依赖服务失败导致的
3. 消息积压怎么处理？具体问题具体分析。2步走，控制消息进来，加快消费速度
	1. 临时限流，临时扩容
		1. 如果消费者扩容了还是堆积怎么办？
	2. 查看log 分析原因，是否消费者端出现问题？
		1. 如果不是的话，考虑增加 queue 或者增加 topic
		2. 是的话，看为什么堵着了，是本来处理的慢（解决方法：批处理）还是下游业务出问题了
4. kafka 的 rebalance
	1. 节点的增加/删除/宕机
	2. topic 的改动
	3. partition 的增加
	4. 消费者 group 的增加/删除/崩溃（心跳超时）
5. MQ 的落盘是怎么落盘的？（是怎么做到高吞吐量的）
	1. 用 page cache 和 aof 落盘。 先写入内存，再异步写磁盘
	2. 异步写磁盘的策略：
		1. 固定间隔时间刷盘
		2. 收到固定容量的messge刷盘
	3. 零拷贝：系统调用避免两次数据复制和上下文切换
6. MQ 的是如何保证消息不丢失
	1. 生产方 ack， 0 （不在乎是否真的写入）1（leader 写入）all （多数写入）
	2. 队列：异步写磁盘 and 多数写入确认机制
	3. 消费者：手动确认 offset
	4. 为什么需要生产者配置ack而不是集群来保证消息不丢？
		1. 中间件的设计思想是把选择权交给用户
		2. 永远是配置驱动，更加灵活
		3. ack=all + min.insync.replicas=2 这种强制同步吞吐量要比 ack=1 慢3倍 ，但是有些场景是不需要这么高的确认的，比如日志和监控系统。



## DB
1. 读未提交，读提交，可重复读，串行
2. 怎么分析慢 SQL
	1. 是否引用索引
	2. 看执行计划: 是否引起了全表扫描
	3. 本身的结构, 是不是加了函数? 是不是加了 OR 关键字? 是不是子查询或者嵌套很深?
	4. 查回来的数据量特别大. 是不是 join 的表很大? join是不是用了索引? 分页是否分的不合理?
	5. 是否频繁执行（高频 + 慢 → 大杀器）
3. 一条sql 尽管加了索引, 但是还是引起了全表扫描
	1. 可能是**范围查询**引起后续索引字段失效
	2. **使用了函数或表达式**：如 `WHERE YEAR(birthday) = 2020`，即使 `birthday` 有索引，也会失效
	3. **LIKE 前模糊**：如 `LIKE '%abc'` 会导致后续字段无法索引
	4. 当然主要还是要看执行计划, 看 type, 看 key 看 rows
4. b+ 树
	1. b+ 树只有叶子结点存数据
5. 聚簇索引和非聚簇（二级索引）
	1. 一个是主键一个是字段索引
	2. 一个存行数，一个存索引字段和主键
	3. 只要语句中包含二级索引没有的字段都会引起回表
6. 事务和分布式事务
	1. 分布式事务 2阶段提交 and 侵入式 TCC （预提交字段）
7. 分库分表
	1. 垂直分库 -》避免业务抢占连接池
	2. 水平分库
		1. 间隔取模 分库，难以水平扩展
		2. consistent hashing 分库


## 锁
1. 乐观锁: CAS **乐观锁一般和版本号机制一起使用，比如数据库中通过 `version` 字段** 可以看看 zookeeper的 mini transaction[[zookeeper#mini transaction]]
	1. 读
	2. 再次读, 如果和第一次结果一样就写, 如果不一样就不写
2. 悲观锁
3. 可重入锁: 允许同一个线程重复获得同一把锁，不会死锁
	1. 它和悲观锁的不同在于它记了锁的ower 和 加锁的次数
```
Thread A calls lock():
    if state == 0:
        -> lock granted, set owner = A, state = 1
    else if owner == A:
        -> reentrant, state++
    else:
        -> block and queue

Thread A calls unlock():
    -> state--
    if state == 0:
        -> set owner = null, wake next thread
```
2. 好处就是避免死锁, 以及调用多个方法不用关系是不是已经被加锁了
3. sync vs lock 接口
	1. java 大部分 aqs 是 cas + queue



## Redis
1. redis 哨兵集群，需要至少3个哨兵节点来避免脑裂
2. string list hash set zset（有序set）
3. redis 某一分片过热, 可能是什么原因?
	1. 某个原因都 hashing到一片去了
	2. hot key
	3. 业务逻辑导致访问集中到某分片
4. 讲一下redis 漏桶限流, 有没有了解过滑动窗口限流
	1. 滑动窗口: 比如 60秒之内只允许100个请求
	2. 桶, 漏桶 (册那, 昨晚刚看的就忘了fk)
5. redis 锁, (setnt+Lua) reddision 的好处?
	1. zset 可以做公平锁, 参考zookeeper的 **临时顺序节点实现锁， 有先后顺序** redis 公平锁的先后顺序就是value是 timestamp
	2. 一套脚本, 有很多个要注意, 需要处理的点, 写了很多次, 那么这套脚本, 或者说这套流程就可以被抽出来做个轮子. 不需要再关注内部实现和一些边界问题. 比如说续期
6. 同步请求怎么幂等
	1. memory cache, parameter 做 hashing 做key
	2. ![[Pasted image 20250626152921.png]]