wechat 1.4
zhi 64000

gongshang 335000
 gold 80 +180 165600

 gupiao 60000

50 14

64 + 20

84



340 920


64-
312800

32
10
8



3400 

事务在生成 Read View（快照）那一刻，数据库里真实的数据状态可能在变化，
那它拿着一个静态的快照去读，怎么保证读到的是一致的呢？”


Read View 并不是保存数据内容的快照，而是保存 “可见性规则的快照”


逻辑上你的事务视角没变。

就是即使查到的数据不一致，但是可见性是一致的。并且数据是递增的，完全可以找到就数据，不用纠结。


事务的快照，决定了可见性，即使两次select之间的行数据差别是，没执行，执行了，甚至提交了，都在一个范围内。


数据是增加的，保证了不会漏掉消息。

min-max之间提交了的可能比min早，并且已经提交了，但是小雨min的肯定是提交了，大于max肯定不可见，那其实就是排除法找到活跃的不可见的事务



## 其实好的程序设计是叠加出来的，不是一次，，
就比如 sal， softirq 和 定时器 以及ack
比如 producer 对于zk，错误机制，定时轮训，共同保障了把这件事情完成，这跟传统的编程方式不同

## 软件之间的协作
就像arraylist自己会扩容一样，那软件也可以主动维护自己的状态，而不是单单被动处理请求。


## 通过网络来实现装饰器

## producer 和 service 协商共同解决了这个问题。


## 那就是说对于monitor的互斥操作是字段级别的，不是整个对象级别的，对于对象的修改么，通过代码逻辑也就是校验owner是不是自己然后才能做修改来限制的。
